#!/bin/sh

BACKUP_ROOT=$1
SERVER_NAME=`uname -n`
BACKUP_PATH="${BACKUP_ROOT}/${SERVER_NAME}"
USER=`whoami`
DATE=`date +%Y%m%d%H%M%S`
EMAIL="no-reply@${SERVER_NAME}"

if [ "${USER}" = "root" ]; then
    echo "You shouldn't be logged as root"
    exit 1
fi

if [ -z "${BACKUP_ROOT}" ]; then
    echo "No backup root supplied"
    exit 1
fi

git config --global user.name "${SERVER_NAME}"
git config --global user.email "${EMAIL}"

sudo mkdir -p "${BACKUP_PATH}" && cd "${BACKUP_PATH}"
sudo cp --parents -r /etc .
sudo cp --parents -r /var/spool/cron .
sudo rm -f etc/shadow etc/shadow- etc/gshadow etc/gshadow-
sudo chown -R ${USER}:${USER} ${BACKUP_ROOT}

cd ${BACKUP_ROOT}
test -d "${BACKUP_ROOT}/.git" || git init
git add "${SERVER_NAME}" && git commit -a -m "${DATE}"
git pull origin master && git push origin master
